### ISSUE TITLE
Fix Getting Started link in README.md

### ISSUE THREAD

**Issue by wilsonianb** [ovrclk/disco#18]
### Issue type
typo

### What happened
Clicked [Getting Started](https://github.com/ovrclk/disco/blob/master/getting-started) in README.md and got 404

### What did you expect to happen
[Getting Started](https://github.com/ovrclk/disco/blob/master/getting-started.md)

### Environment
github

## Next steps

You may [join developer chat](https://akash.network/chat) for community support.

**Comment by gosuri** [comment]
thx @wilsonianb :)
